name: Chronologyarts
favicon: null
layout_spectrum: 0.7007169
typography_spectrum: 0.1863799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73420574-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0E0E0E'
    - '#F0E9DE'
    - '#BD8F66'
    - '#E0C5A4'
    - '#5C5B54'
  brandStrength: 1
  lightness: 0.7401434
  saturation: 1
  rhythmicContrast: 1
purpose: []
